"""MediaMTX supervision: generate its config and keep the process alive.

MediaMTX no longer owns the camera. It accepts an H.264 stream published by
CameraService over local RTSP and re-serves it to browsers as WebRTC (WHEP).
"""

from __future__ import annotations

import asyncio
import shutil
import textwrap
from pathlib import Path
from typing import Any

from ..core.service import Service

RUNTIME_DIR = Path.home() / ".wasty"


class MediamtxService(Service):
    name = "mediamtx"

    def __init__(self, ctx):
        super().__init__(ctx)
        self.cfg = ctx.config.mediamtx
        self.proc: asyncio.subprocess.Process | None = None
        self.config_path = RUNTIME_DIR / "mediamtx.yml"
        self.log_path = RUNTIME_DIR / "mediamtx.log"

    def _binary(self) -> str | None:
        if Path(self.cfg.binary).exists():
            return self.cfg.binary
        return shutil.which("mediamtx")

    def _write_config(self) -> None:
        RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
        self.config_path.write_text(
            textwrap.dedent(
                f"""\
                # Auto-generated by wasty — do not edit by hand
                logLevel: info
                rtsp: yes
                rtspAddress: :{self.cfg.rtsp_port}
                webrtc: yes
                webrtcAddress: :{self.cfg.webrtc_port}
                hls: no
                rtmp: no
                srt: no

                paths:
                  {self.cfg.stream_name}: {{}}
                """
            )
        )

    async def _spawn(self) -> None:
        binary = self._binary()
        if binary is None:
            raise RuntimeError(
                f"mediamtx binary not found at {self.cfg.binary} or on PATH; "
                "run scripts/install.sh or set mediamtx.binary in config"
            )
        self._write_config()
        log_fh = open(self.log_path, "ab")
        self.proc = await asyncio.create_subprocess_exec(
            binary, str(self.config_path), stdout=log_fh, stderr=log_fh
        )
        self.log.info("mediamtx started (pid %d)", self.proc.pid)

    async def start(self) -> None:
        if self.ctx.config.system.mock and self._binary() is None:
            self.log.warning("mock mode and no mediamtx binary; streaming disabled")
            return
        await self._spawn()

    async def run(self) -> None:
        while True:
            if self.proc is not None:
                returncode = await self.proc.wait()
                self.log.warning("mediamtx exited (%s); restarting", returncode)
                self.proc = None
                await asyncio.sleep(1)
                await self._spawn()
            else:
                await asyncio.sleep(5)

    async def stop(self) -> None:
        if self.proc is not None and self.proc.returncode is None:
            self.proc.terminate()
            try:
                await asyncio.wait_for(self.proc.wait(), timeout=5)
            except TimeoutError:
                self.proc.kill()
        self.proc = None

    def rtsp_url(self) -> str:
        return f"rtsp://127.0.0.1:{self.cfg.rtsp_port}/{self.cfg.stream_name}"

    def status(self) -> dict[str, Any]:
        running = self.proc is not None and self.proc.returncode is None
        return {
            "process": "running" if running else "down",
            "webrtc_port": self.cfg.webrtc_port,
            "stream": self.cfg.stream_name,
        }
